services:
  backend:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./fastapi:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./pages
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app
    command: npm run dev
